### ISSUE TITLE
annotation attribute in CoveragePlot function

### ISSUE THREAD

**Issue by pengxin2019** [stuart-lab/signac#1294]
Hi Signac team,
I have an Seurat object and its information is here:
Here is the description of my `Seurat` object `integrated` which was annotated using a `gtf` file

```
> integrated
An object of class Seurat 
130479 features across 15626 samples within 2 assays 
Active assay: peaks (110444 features, 110272 variable features)
 1 other assay present: RNA
 3 dimensional reductions calculated: integrated_lsi, umap, lsi
```

I was trying to set annotation="transcript" for `CoveragePlot` function  in oder to plot all transcripts in `gene track `since you mentioned that the longest transcript is used by default. However, I found this error below. Can you give me some comments?

```
 p <- CoveragePlot(
  object = integrated,
  region = "2-151108982-151113383",#
  extend.upstream = 20000,
  extend.downstream = 20000,
  show.bulk = TRUE,
  ranges = ranges.show,
  region.highlight = ranges.show,
  annotation = "transcript"
)
```
error:
`Error in if (annotation) { : argument is not interpretable as logical
`
The annotation of this Seurat object look like this:
```
> Annotation(integrated)
GRanges object with 1530978 ranges and 21 metadata columns:
                  seqnames    ranges strand |   source       type     score
                     <Rle> <IRanges>  <Rle> | <factor>   <factor> <numeric>
        [1]              1    1-3782      + |  ensembl gene              NA
        [2]              1    1-3780      + |  ensembl transcript        NA
        [3]              1    1-2465      + |  ensembl exon              NA
        [4]              1 3118-3780      + |  ensembl exon              NA
        [5]              1  792-3782      + |  ensembl transcript        NA
        ...            ...       ...    ... .      ...        ...       ...
  [1530974] AEMK02000302.1 5535-5587      - |  ensembl exon              NA
  [1530975] AEMK02000302.1      4-47      - |  ensembl exon              NA
  [1530976] AEMK02000302.1    4-8300      - |  ensembl transcript        NA
  [1530977] AEMK02000302.1 8159-8300      - |  ensembl exon              NA
  [1530978] AEMK02000302.1      4-47      - |  ensembl exon              NA
                phase            gene_id gene_version gene_source gene_biotype
            <integer>        <character>  <character> <character>  <character>
        [1]      <NA> ENSSSCG00000048769            1     ensembl       lncRNA
        [2]      <NA> ENSSSCG00000048769            1     ensembl       lncRNA
        [3]      <NA> ENSSSCG00000048769            1     ensembl       lncRNA
        [4]      <NA> ENSSSCG00000048769            1     ensembl       lncRNA
        [5]      <NA> ENSSSCG00000048769            1     ensembl       lncRNA
        ...       ...                ...          ...         ...          ...
  [1530974]      <NA> ENSSSCG00000049924            1     ensembl       lncRNA
  [1530975]      <NA> ENSSSCG00000049924            1     ensembl       lncRNA
  [1530976]      <NA> ENSSSCG00000049924            1     ensembl       lncRNA
  [1530977]      <NA> ENSSSCG00000049924            1     ensembl       lncRNA
  [1530978]      <NA> ENSSSCG00000049924            1     ensembl       lncRNA
                 transcript_id transcript_version transcript_source
                   <character>        <character>       <character>
        [1]               <NA>               <NA>              <NA>
        [2] ENSSSCT00000066540                  1           ensembl
        [3] ENSSSCT00000066540                  1           ensembl
        [4] ENSSSCT00000066540                  1           ensembl
        [5] ENSSSCT00000078085                  1           ensembl
        ...                ...                ...               ...
  [1530974] ENSSSCT00000066525                  1           ensembl
  [1530975] ENSSSCT00000066525                  1           ensembl
  [1530976] ENSSSCT00000068345                  1           ensembl
  [1530977] ENSSSCT00000068345                  1           ensembl
  [1530978] ENSSSCT00000068345                  1           ensembl
            transcript_biotype exon_number            exon_id exon_version
                   <character> <character>        <character>  <character>
        [1]               <NA>        <NA>               <NA>         <NA>
        [2]             lncRNA        <NA>               <NA>         <NA>
        [3]             lncRNA           1 ENSSSCE00000399651            1
        [4]             lncRNA           2 ENSSSCE00000450299            1
        [5]             lncRNA        <NA>               <NA>         <NA>
        ...                ...         ...                ...          ...
  [1530974]             lncRNA           2 ENSSSCE00000399377            1
  [1530975]             lncRNA           3 ENSSSCE00000418429            1
  [1530976]             lncRNA        <NA>               <NA>         <NA>
  [1530977]             lncRNA           1 ENSSSCE00000453271            1
  [1530978]             lncRNA           2 ENSSSCE00000418429            1
             protein_id protein_version   gene_name transcript_name
            <character>     <character> <character>     <character>
        [1]        <NA>            <NA>        <NA>            <NA>
        [2]        <NA>            <NA>        <NA>            <NA>
        [3]        <NA>            <NA>        <NA>            <NA>
        [4]        <NA>            <NA>        <NA>            <NA>
        [5]        <NA>            <NA>        <NA>            <NA>
        ...         ...             ...         ...             ...
  [1530974]        <NA>            <NA>        <NA>            <NA>
  [1530975]        <NA>            <NA>        <NA>            <NA>
  [1530976]        <NA>            <NA>        <NA>            <NA>
  [1530977]        <NA>            <NA>        <NA>            <NA>
  [1530978]        <NA>            <NA>        <NA>            <NA>
            projection_parent_transcript         tag
                             <character> <character>
        [1]                         <NA>        <NA>
        [2]                         <NA>        <NA>
        [3]                         <NA>        <NA>
        [4]                         <NA>        <NA>
        [5]                         <NA>        <NA>
        ...                          ...         ...
  [1530974]                         <NA>        <NA>
  [1530975]                         <NA>        <NA>
  [1530976]                         <NA>        <NA>
  [1530977]                         <NA>        <NA>
  [1530978]                         <NA>        <NA>
  -------
  seqinfo: 351 sequences from an unspecified genome; no seqlengths
```
Here is the sessionInfo():

```
>  sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 18.04 LTS

Matrix products: default
BLAS/LAPACK: /opt/miniconda3/envs/r4/lib/libopenblasp-r0.3.10.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] dplyr_1.0.7         patchwork_1.1.1     ggplot2_3.3.5      
 [4] GenomeInfoDb_1.26.7 IRanges_2.24.1      S4Vectors_0.28.1   
 [7] BiocGenerics_0.36.1 SeuratObject_4.0.2  Seurat_4.0.5       
[10] Signac_1.4.0       

loaded via a namespace (and not attached):
  [1] Rtsne_0.15             colorspace_2.0-2       deldir_1.0-6          
  [4] ellipsis_0.3.2         ggridges_0.5.3         lsa_0.73.2            
  [7] XVector_0.30.0         GenomicRanges_1.42.0   spatstat.data_2.1-0   
 [10] farver_2.1.0           leiden_0.3.9           listenv_0.8.0         
 [13] SnowballC_0.7.0        ggrepel_0.9.1          fansi_0.5.0           
 [16] codetools_0.2-18       splines_4.0.5          docopt_0.7.1          
 [19] RcppRoll_0.3.0         polyclip_1.10-0        jsonlite_1.7.2        
 [22] Rsamtools_2.6.0        ica_1.0-2              cluster_2.1.2         
 [25] png_0.1-7              uwot_0.1.10            ggforce_0.3.3         
 [28] shiny_1.7.1            sctransform_0.3.2      spatstat.sparse_2.0-0 
 [31] compiler_4.0.5         httr_1.4.2             assertthat_0.2.1      
 [34] Matrix_1.3-4           fastmap_1.1.0          lazyeval_0.2.2        
 [37] tweenr_1.0.2           later_1.3.0            htmltools_0.5.2       
 [40] tools_4.0.5            igraph_1.2.8           gtable_0.3.0          
 [43] glue_1.6.2             GenomeInfoDbData_1.2.4 RANN_2.6.1            
 [46] reshape2_1.4.4         fastmatch_1.1-3        Rcpp_1.0.7            
 [49] slam_0.1-48            scattermore_0.7        vctrs_0.3.8           
 [52] Biostrings_2.58.0      nlme_3.1-153           ggseqlogo_0.1         
 [55] lmtest_0.9-39          stringr_1.4.0          globals_0.14.0        
 [58] mime_0.12              miniUI_0.1.1.1         lifecycle_1.0.1       
 [61] irlba_2.3.3            goftest_1.2-3          future_1.21.0         
 [64] zlibbioc_1.36.0        MASS_7.3-54            zoo_1.8-9             
 [67] scales_1.1.1           spatstat.core_2.3-1    promises_1.2.0.1      
 [70] spatstat.utils_2.2-0   RColorBrewer_1.1-2     reticulate_1.22       
 [73] pbapply_1.5-0          gridExtra_2.3          rpart_4.1-15          
 [76] stringi_1.7.5          BiocParallel_1.24.1    rlang_0.4.12          
 [79] pkgconfig_2.0.3        matrixStats_0.62.0     bitops_1.0-7          
 [82] qlcMatrix_0.9.7        lattice_0.20-45        ROCR_1.0-11           
 [85] purrr_0.3.4            tensor_1.5             htmlwidgets_1.5.4     
 [88] cowplot_1.1.1          tidyselect_1.1.1       parallelly_1.28.1     
 [91] RcppAnnoy_0.0.19       plyr_1.8.6             magrittr_2.0.1        
 [94] R6_2.5.1               generics_0.1.1         DBI_1.1.1             
 [97] withr_2.4.2            mgcv_1.8-38            pillar_1.6.4          
[100] fitdistrplus_1.1-6     survival_3.2-13        abind_1.4-5           
[103] RCurl_1.98-1.5         tibble_3.1.6           future.apply_1.8.1    
[106] crayon_1.4.2           KernSmooth_2.23-20     utf8_1.2.2            
[109] spatstat.geom_2.3-0    plotly_4.10.0          grid_4.0.5            
[112] data.table_1.14.2      sparsesvd_0.2          digest_0.6.28         
[115] xtable_1.8-4           tidyr_1.1.4            httpuv_1.6.3          
[118] munsell_0.5.0          viridisLite_0.4.0     
```

**Comment by timoast** [comment]
This feature was added in Signac 1.7.0 (https://github.com/stuart-lab/signac/blob/master/NEWS.md#signac-170), please update to the latest release

**Comment by pengxin2019** [comment]
Hi Tim,
I just tried new version of Signac but i got another error.
Here is my code:
```
DefaultAssay(integrated) <- 'peaks'
Annotation(integrated)

ranges.show <- StringToGRanges("2-151108982-151113383")
p <- CoveragePlot(
  object = integrated,
  region = "2-151108982-151113383",#CSF1R
  extend.upstream = 25000,
  extend.downstream = 25000,
  show.bulk = TRUE,
  ranges = ranges.show,
  region.highlight = ranges.show,
  annotation="transcript"
)
```
Here is my error:

`Error in cutmat[[1]] : this S4 class is not subsettable
`
 ```
sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] dplyr_1.0.7         patchwork_1.1.1     ggplot2_3.3.5      
 [4] GenomeInfoDb_1.30.1 IRanges_2.28.0      S4Vectors_0.32.3   
 [7] BiocGenerics_0.40.0 SeuratObject_4.0.4  Seurat_4.1.0       
[10] Signac_1.8.0       

loaded via a namespace (and not attached):
  [1] Rtsne_0.15             colorspace_2.0-2       deldir_1.0-5          
  [4] ellipsis_0.3.2         ggridges_0.5.3         XVector_0.34.0        
  [7] GenomicRanges_1.46.1   rstudioapi_0.13        spatstat.data_2.1-0   
 [10] farver_2.1.0           leiden_0.3.9           listenv_0.8.0         
 [13] ggrepel_0.9.1          fansi_0.5.0            codetools_0.2-18      
 [16] splines_4.1.1          polyclip_1.10-0        RcppRoll_0.3.0        
 [19] jsonlite_1.7.2         Rsamtools_2.10.0       ica_1.0-2             
 [22] cluster_2.1.2          png_0.1-7              uwot_0.1.11           
 [25] shiny_1.7.1            sctransform_0.3.3      spatstat.sparse_2.0-0 
 [28] compiler_4.1.1         httr_1.4.2             assertthat_0.2.1      
 [31] Matrix_1.3-4           fastmap_1.1.0          lazyeval_0.2.2        
 [34] later_1.3.0            htmltools_0.5.2        tools_4.1.1           
 [37] igraph_1.2.11          gtable_0.3.0           glue_1.4.2            
 [40] GenomeInfoDbData_1.2.7 RANN_2.6.1             reshape2_1.4.4        
 [43] fastmatch_1.1-3        Rcpp_1.0.7             scattermore_0.7       
 [46] vctrs_0.3.8            Biostrings_2.62.0      nlme_3.1-152          
 [49] lmtest_0.9-39          stringr_1.4.0          globals_0.14.0        
 [52] mime_0.12              miniUI_0.1.1.1         lifecycle_1.0.1       
 [55] irlba_2.3.5            goftest_1.2-3          future_1.22.1         
 [58] zlibbioc_1.40.0        MASS_7.3-54            zoo_1.8-9             
 [61] scales_1.1.1           spatstat.core_2.3-0    promises_1.2.0.1      
 [64] spatstat.utils_2.2-0   parallel_4.1.1         RColorBrewer_1.1-2    
 [67] reticulate_1.24        pbapply_1.5-0          gridExtra_2.3         
 [70] rpart_4.1-15           stringi_1.7.5          BiocParallel_1.28.3   
 [73] rlang_0.4.11           pkgconfig_2.0.3        matrixStats_0.61.0    
 [76] bitops_1.0-7           lattice_0.20-44        ROCR_1.0-11           
 [79] purrr_0.3.4            tensor_1.5             labeling_0.4.2        
 [82] htmlwidgets_1.5.4      cowplot_1.1.1          tidyselect_1.1.1      
 [85] parallelly_1.28.1      RcppAnnoy_0.0.19       plyr_1.8.6            
 [88] magrittr_2.0.1         R6_2.5.1               generics_0.1.0        
 [91] DBI_1.1.1              withr_2.4.2            mgcv_1.8-36           
 [94] pillar_1.6.3           fitdistrplus_1.1-6     survival_3.2-11       
 [97] abind_1.4-5            RCurl_1.98-1.5         tibble_3.1.5          
[100] future.apply_1.8.1     crayon_1.4.1           KernSmooth_2.23-20    
[103] utf8_1.2.2             spatstat.geom_2.3-0    plotly_4.10.0         
[106] grid_4.1.1             data.table_1.14.2      digest_0.6.28         
[109] xtable_1.8-4           tidyr_1.1.4            httpuv_1.6.3          
[112] munsell_0.5.0          viridisLite_0.4.0     
```

**Comment by timoast** [comment]
Can you show the output of `traceback()` after getting the error?

**Comment by pengxin2019** [comment]
> traceback()
5: CoverageTrack(cutmat = cutmat[[1]], region = region, group.scale.factors = bulk.scale.factor, 
       scale.factor = scale.factor, window = window, ymax = ymax, 
       obj.groups = bulk.groups, downsample.rate = downsample.rate, 
       max.downsample = max.downsample)
4: SingleCoveragePlot(object = object, region = region[[x]], features = features, 
       expression.assay = expression.assay, expression.slot = expression.slot, 
       show.bulk = show.bulk, annotation = annotation, peaks = peaks, 
       peaks.group.by = peaks.group.by, ranges = ranges, ranges.group.by = ranges.group.by, 
       ranges.title = ranges.title, region.highlight = region.highlight, 
       assay = assay, split.assays = split.assays, assay.scale = assay.scale, 
       links = links, tile = tile, tile.size = tile.size, tile.cells = tile.cells, 
       bigwig = bigwig, bigwig.type = bigwig.type, bigwig.scale = bigwig.scale, 
       group.by = group.by, window = window, ymax = ymax, scale.factor = scale.factor, 
       extend.upstream = extend.upstream, extend.downstream = extend.downstream, 
       cells = cells, idents = idents, sep = sep, heights = heights, 
       max.downsample = max.downsample, downsample.rate = downsample.rate)
3: FUN(X[[i]], ...)
2: lapply(X = seq_along(region), FUN = function(x) {
       SingleCoveragePlot(object = object, region = region[[x]], 
           features = features, expression.assay = expression.assay, 
           expression.slot = expression.slot, show.bulk = show.bulk, 
           annotation = annotation, peaks = peaks, peaks.group.by = peaks.group.by, 
           ranges = ranges, ranges.group.by = ranges.group.by, ranges.title = ranges.title, 
           region.highlight = region.highlight, assay = assay, split.assays = split.assays, 
           assay.scale = assay.scale, links = links, tile = tile, 
           tile.size = tile.size, tile.cells = tile.cells, bigwig = bigwig, 
           bigwig.type = bigwig.type, bigwig.scale = bigwig.scale, 
           group.by = group.by, window = window, ymax = ymax, scale.factor = scale.factor, 
           extend.upstream = extend.upstream, extend.downstream = extend.downstream, 
           cells = cells, idents = idents, sep = sep, heights = heights, 
           max.downsample = max.downsample, downsample.rate = downsample.rate)
   })
1: CoveragePlot(object = integrated, region = "2-151108982-151113383", 
       extend.upstream = 25000, extend.downstream = 25000, show.bulk = TRUE, 
       ranges = ranges.show, region.highlight = ranges.show, annotation = "transcript")

**Comment by timoast** [comment]
This should now be fixed on the the develop branch, see install instructions here: https://stuartlab.org/signac/articles/install.html#development-version

**Comment by pengxin2019** [comment]
Hi Tim,
I took me a while to download it since I had permission issue on our hpc.

Unfortunately I still have an error. The `integrated` object is the same as what I have described.
here is my code:
 ```
ranges.show <- StringToGRanges("2-151108982-151113383")
p <- CoveragePlot(
  object = integrated,
  region = "2-151108982-151113383",#CSF1R
  extend.upstream = 25000,
  extend.downstream = 25000,
  show.bulk = TRUE,
  # ranges = ranges.show,
  region.highlight = ranges.show,
  annotation="transcript"
)
```
here is the error I got after script above was issued:
`Error in cutmat[[1]] : this S4 class is not subsettable
`
```
sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] dplyr_1.0.7         patchwork_1.1.1     ggplot2_3.3.5      
 [4] GenomeInfoDb_1.30.1 IRanges_2.28.0      S4Vectors_0.32.3   
 [7] BiocGenerics_0.40.0 SeuratObject_4.0.4  Seurat_4.1.0       
[10] Signac_1.8.0       

loaded via a namespace (and not attached):
  [1] fastmatch_1.1-3        plyr_1.8.6             igraph_1.2.11         
  [4] lazyeval_0.2.2         splines_4.1.1          BiocParallel_1.28.3   
  [7] listenv_0.8.0          scattermore_0.7        usethis_2.0.1         
 [10] digest_0.6.28          htmltools_0.5.2        fansi_0.5.0           
 [13] magrittr_2.0.1         memoise_2.0.0          tensor_1.5            
 [16] cluster_2.1.2          ROCR_1.0-11            remotes_2.4.1         
 [19] globals_0.14.0         Biostrings_2.62.0      matrixStats_0.61.0    
 [22] spatstat.sparse_2.0-0  prettyunits_1.1.1      colorspace_2.0-2      
 [25] ggrepel_0.9.1          callr_3.7.0            crayon_1.4.1          
 [28] RCurl_1.98-1.5         jsonlite_1.7.2         spatstat.data_2.1-0   
 [31] survival_3.2-11        zoo_1.8-9              glue_1.4.2            
 [34] polyclip_1.10-0        gtable_0.3.0           zlibbioc_1.40.0       
 [37] XVector_0.34.0         leiden_0.3.9           pkgbuild_1.2.0        
 [40] future.apply_1.8.1     abind_1.4-5            scales_1.1.1          
 [43] DBI_1.1.1              miniUI_0.1.1.1         Rcpp_1.0.7            
 [46] viridisLite_0.4.0      xtable_1.8-4           reticulate_1.24       
 [49] spatstat.core_2.3-0    htmlwidgets_1.5.4      httr_1.4.2            
 [52] RColorBrewer_1.1-2     ellipsis_0.3.2         ica_1.0-2             
 [55] farver_2.1.0           pkgconfig_2.0.3        uwot_0.1.11           
 [58] deldir_1.0-5           utf8_1.2.2             tidyselect_1.1.1      
 [61] rlang_0.4.11           reshape2_1.4.4         later_1.3.0           
 [64] munsell_0.5.0          tools_4.1.1            cachem_1.0.6          
 [67] cli_3.0.1              generics_0.1.0         devtools_2.4.2        
 [70] ggridges_0.5.3         stringr_1.4.0          fastmap_1.1.0         
 [73] goftest_1.2-3          processx_3.5.2         fs_1.5.0              
 [76] fitdistrplus_1.1-6     purrr_0.3.4            RANN_2.6.1            
 [79] pbapply_1.5-0          future_1.22.1          nlme_3.1-152          
 [82] mime_0.12              RcppRoll_0.3.0         compiler_4.1.1        
 [85] rstudioapi_0.13        plotly_4.10.0          curl_4.3.2            
 [88] png_0.1-7              testthat_3.1.0         spatstat.utils_2.2-0  
 [91] tibble_3.1.5           stringi_1.7.5          ps_1.6.0              
 [94] desc_1.4.0             lattice_0.20-44        Matrix_1.3-4          
 [97] vctrs_0.3.8            pillar_1.6.3           lifecycle_1.0.1       
[100] spatstat.geom_2.3-0    lmtest_0.9-39          RcppAnnoy_0.0.19      
[103] data.table_1.14.2      cowplot_1.1.1          bitops_1.0-7          
[106] irlba_2.3.5            httpuv_1.6.3           GenomicRanges_1.46.1  
[109] R6_2.5.1               promises_1.2.0.1       KernSmooth_2.23-20    
[112] gridExtra_2.3          parallelly_1.28.1      sessioninfo_1.1.1     
[115] codetools_0.2-18       MASS_7.3-54            assertthat_0.2.1      
[118] pkgload_1.2.2          rprojroot_2.0.2        withr_2.4.2           
[121] sctransform_0.3.3      Rsamtools_2.10.0       GenomeInfoDbData_1.2.7
[124] mgcv_1.8-36            parallel_4.1.1         grid_4.1.1            
[127] rpart_4.1-15           tidyr_1.1.4            Rtsne_0.15            
[130] shiny_1.7.1           
```

Can you give me any further comments?

Thanks

**Comment by timoast** [comment]
The session info shows that you still have the older version loaded, you'll need to update the package (see instructions linked above) and verify that the version that's loaded in your R session is 1.8.0.9003
